version: 2
jobs:
  check:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm run check
          command: npm run check
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm test
          command: npm test
workflows:
  version: 2
  check:
    jobs:
      - check
  test:
    jobs:
      - test
